import 'dart:convert';
import 'dart:io';
import 'package:path/path.dart' as p;
import 'context.dart';
import 'process.dart';

/// Linux Flutter compilation uses only container compilers and SDKs. Existing
/// resolved dependencies are mounted read-only; no credentials/home are shared.
final class LinuxToolboxBuilder {
  LinuxToolboxBuilder(this.repo, this.runner, this.version);
  final Repository repo;
  final CommandRunner runner;
  final String version;
  static const relativeBuildDirectory = '../../build/toolbox/flutter';
  String get buildDirectory => repo.path('build/toolbox/flutter');
  String get sdkRoot => repo.path('build/toolbox/linux-sdk/$version');
  FlutterSdk get sdk => FlutterSdk(sdkRoot);
  Map<String, String> get environment => {
    'HOME': repo.path('build/toolbox/linux-home'),
    'XDG_CONFIG_HOME': repo.path('build/toolbox/linux-home/.config'),
    'PUB_CACHE': repo.path('build/toolbox/linux-pub-cache'),
    'CI': 'true',
    'FLUTTER_SUPPRESS_ANALYTICS': 'true',
    'DART_SUPPRESS_ANALYTICS': 'true',
  };

  Future<void> prepare(BuildConfig config) async {
    if (!RegExp(r'^[a-zA-Z0-9._-]+$').hasMatch(version)) {
      throw BuildFailure('Invalid Toolbox SDK revision');
    }
    for (final path in [
      environment['HOME']!,
      environment['PUB_CACHE']!,
      p.dirname(sdkRoot),
    ]) {
      Directory(path).createSync(recursive: true);
    }
    final marker = File(p.join(sdkRoot, '.tempo-container-sdk'));
    if (marker.existsSync() && marker.readAsStringSync() == version) return;
    final staging = Directory('$sdkRoot.staging');
    if (staging.existsSync()) staging.deleteSync(recursive: true);
    FlutterSdk? cached;
    try {
      final candidate = await FlutterSdk.discover(
        config,
        runner,
        version: version,
      );
      final dart = File(candidate.dart);
      if (dart.existsSync()) {
        final input = dart.openSync();
        try {
          final magic = input.readSync(4);
          if (magic.length == 4 &&
              magic[0] == 0x7f &&
              magic[1] == 69 &&
              magic[2] == 76 &&
              magic[3] == 70)
            cached = FlutterSdk(
              Directory(candidate.root).resolveSymbolicLinksSync(),
            );
        } finally {
          input.closeSync();
        }
      }
    } on BuildFailure {
      // No host Flutter/FVM is required; bootstrap the pinned SDK in-container.
    }
    final container = Toolchain(repo, runner);
    if (cached != null) {
      await container.run(
        ['cp', '-a', cached.root, staging.path],
        environment: environment,
        readOnlyPaths: [cached.root],
      );
    } else {
      await container.run([
        'git',
        'clone',
        '--filter=blob:none',
        '--no-checkout',
        'https://github.com/flutter/flutter.git',
        staging.path,
      ], environment: environment);
      await container.run([
        'git',
        '-C',
        staging.path,
        'checkout',
        '--detach',
        version,
      ], environment: environment);
    }
    if (FileSystemEntity.typeSync(staging.path, followLinks: false) !=
        FileSystemEntityType.directory) {
      throw BuildFailure('Container SDK staging must be a real directory');
    }
    File(
      p.join(staging.path, '.tempo-container-sdk'),
    ).writeAsStringSync(version);
    if (Directory(sdkRoot).existsSync())
      Directory(sdkRoot).deleteSync(recursive: true);
    staging.renameSync(sdkRoot);
  }

  /// The package config is generated by ordinary dependency resolution. Only
  /// package roots outside the checkout need additional read-only mounts.
  List<String> dependencyMounts(String directory) {
    final config = File(p.join(directory, '.dart_tool/package_config.json'));
    if (!config.existsSync()) {
      throw BuildFailure(
        'Resolve dependencies for $directory before the cached Linux container build. Private dependencies must be available locally; no SSH credentials are mounted automatically.',
      );
    }
    final data = jsonDecode(config.readAsStringSync()) as Map<String, dynamic>;
    final paths = <String>{};
    for (final package in data['packages'] as List) {
      final uri = config.uri.resolve((package as Map)['rootUri'] as String);
      if (uri.scheme != 'file')
        throw BuildFailure('Expected a local resolved package: $uri');
      final path = p.normalize(uri.toFilePath());
      if (!Directory(path).existsSync())
        throw BuildFailure('Resolved package is missing: $path');
      if (path != repo.root && !p.isWithin(repo.root, path)) paths.add(path);
    }
    return paths.toList()..sort();
  }

  Future<int> run(
    String executable,
    List<String> arguments, {
    required String workingDirectory,
    bool check = true,
  }) async {
    final mounts = dependencyMounts(workingDirectory);
    final toolchain = Toolchain(repo, runner);
    if (executable == sdk.flutter && !_outputConfigured) {
      // Only the container's private Flutter configuration is changed. Native
      // CMake and pkg-config caches must never share the host's build/linux.
      await toolchain.run(
        [sdk.flutter, 'config', '--build-dir=$relativeBuildDirectory'],
        workingDirectory: repo.path('toolbox/app'),
        environment: environment,
      );
      _outputConfigured = true;
    }
    return toolchain.run(
      [executable, ...arguments],
      workingDirectory: workingDirectory,
      environment: environment,
      readOnlyPaths: mounts,
      check: check,
    );
  }

  bool _outputConfigured = false;
}
