[Service]
ExecStartPre=
ExecStartPre=/usr/local/sbin/tempod --init-credentials --credential-group @USER@
Environment=TEMPOD_PROFILE_HOME=/home/@USER@
Environment=TEMPOD_PROFILE_USER=@USER@
Environment=TEMPOD_SD_ROOT=/mnt/sd
Environment=TEMPOD_SETTINGS_FILE=/home/@USER@/.config/tempo/settings.json
